<?php
require_once __DIR__ . '/includes/auth.php';
$user = require_role(['admin']);
if (isset($_GET['delete'])) { $id=(int)$_GET['delete']; $stmt=$conn->prepare('DELETE FROM rooms WHERE room_id=?'); $stmt->bind_param('i',$id); $stmt->execute(); header('Location: admin_manage_rooms.php?success=Room deleted'); exit; }
$edit = null; if(isset($_GET['edit'])){ $id=(int)$_GET['edit']; $stmt=$conn->prepare('SELECT * FROM rooms WHERE room_id=?'); $stmt->bind_param('i',$id); $stmt->execute(); $edit=$stmt->get_result()->fetch_assoc(); }
if($_SERVER['REQUEST_METHOD']==='POST'){
    $id=(int)($_POST['room_id']??0); $name=trim($_POST['room_name']); $code=trim($_POST['room_code']); $type=trim($_POST['room_type']); $loc=trim($_POST['location']); $cap=(int)$_POST['capacity']; $desc=trim($_POST['description']); $price=(float)$_POST['price_per_day']; $status=$_POST['resource_status'];
    if($id>0){ $stmt=$conn->prepare('UPDATE rooms SET room_name=?, room_code=?, room_type=?, location=?, capacity=?, description=?, price_per_day=?, resource_status=? WHERE room_id=?'); $stmt->bind_param('ssssisdsi',$name,$code,$type,$loc,$cap,$desc,$price,$status,$id); $stmt->execute(); $msg='Room updated'; }
    else { $stmt=$conn->prepare('INSERT INTO rooms(room_name,room_code,room_type,location,capacity,description,price_per_day,resource_status) VALUES(?,?,?,?,?,?,?,?)'); $stmt->bind_param('ssssisds',$name,$code,$type,$loc,$cap,$desc,$price,$status); $stmt->execute(); $msg='Room added'; }
    header('Location: admin_manage_rooms.php?success='.urlencode($msg)); exit;
}
$rooms=$conn->query('SELECT * FROM rooms ORDER BY room_name'); $page_title='Admin Manage Rooms'; $active_page='rooms'; include __DIR__ . '/includes/header.php';
?>
<div class="mb-8"><h1 class="text-4xl font-black text-[#36000f]">Admin - Add / Update / Delete Rooms</h1><p class="text-slate-500 mt-2">Maintain room inventory for booking.</p></div>
<div class="grid grid-cols-1 xl:grid-cols-3 gap-6"><form method="post" class="bg-white rounded-xl border border-[#dcc0c2] p-6 shadow-sm space-y-4"><h2 class="text-xl font-black text-[#36000f]"><?= $edit?'Update Room':'Add Room' ?></h2><input type="hidden" name="room_id" value="<?= h($edit['room_id']??0) ?>"><input class="input" name="room_name" required placeholder="Room name" value="<?= h($edit['room_name']??'') ?>"><input class="input" name="room_code" placeholder="Room code" value="<?= h($edit['room_code']??'') ?>"><input class="input" name="room_type" placeholder="Room type" value="<?= h($edit['room_type']??'') ?>"><input class="input" name="location" required placeholder="Location" value="<?= h($edit['location']??'') ?>"><input class="input" name="capacity" type="number" required placeholder="Capacity" value="<?= h($edit['capacity']??'') ?>"><input class="input" name="price_per_day" type="number" step="0.01" placeholder="Price per day" value="<?= h($edit['price_per_day']??'0.00') ?>"><textarea class="input" name="description" placeholder="Description"><?= h($edit['description']??'') ?></textarea><select class="input" name="resource_status"><?php foreach(['available','unavailable','maintenance'] as $s): ?><option value="<?= $s ?>" <?= ($edit['resource_status']??'available')===$s?'selected':'' ?>><?= ucfirst($s) ?></option><?php endforeach; ?></select><button class="btn-primary w-full"><?= $edit?'Update Room':'Add Room' ?></button></form>
<div class="xl:col-span-2 bg-white rounded-xl border border-[#dcc0c2] shadow-sm overflow-hidden"><table class="w-full"><thead><tr><th class="table-th">Room</th><th class="table-th">Location</th><th class="table-th">Capacity</th><th class="table-th">Status</th><th class="table-th">Action</th></tr></thead><tbody><?php while($r=$rooms->fetch_assoc()): ?><tr><td class="table-td font-bold"><?= h($r['room_name']) ?><p class="text-xs text-slate-500"><?= h($r['room_code']) ?> · <?= h($r['room_type']) ?></p></td><td class="table-td"><?= h($r['location']) ?></td><td class="table-td"><?= h($r['capacity']) ?></td><td class="table-td"><span class="badge badge-<?= h($r['resource_status']) ?>"><?= h($r['resource_status']) ?></span></td><td class="table-td"><a class="text-red-900 font-bold" href="?edit=<?= h($r['room_id']) ?>">Edit</a> · <a class="text-red-700 font-bold" onclick="return confirm('Delete this room?')" href="?delete=<?= h($r['room_id']) ?>">Delete</a></td></tr><?php endwhile; ?></tbody></table></div></div>
<?php include __DIR__ . '/includes/footer.php'; ?>
