<?php
require_once __DIR__ . '/includes/auth.php';
$user = require_role(['admin']);
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; if($id!==$user['user_id']){ $stmt=$conn->prepare('DELETE FROM users WHERE user_id=?'); $stmt->bind_param('i',$id); $stmt->execute(); header('Location: admin_manage_users.php?success=User deleted'); exit; } header('Location: admin_manage_users.php?error=You cannot delete your own account'); exit; }
$edit=null; if(isset($_GET['edit'])){ $id=(int)$_GET['edit']; $stmt=$conn->prepare('SELECT * FROM users WHERE user_id=?'); $stmt->bind_param('i',$id); $stmt->execute(); $edit=$stmt->get_result()->fetch_assoc(); }
if($_SERVER['REQUEST_METHOD']==='POST'){
    $id=(int)($_POST['user_id']??0); $name=trim($_POST['full_name']); $email=trim($_POST['email']); $role=$_POST['role']; $phone=trim($_POST['phone_number']); $status=$_POST['account_status']; $pass=$_POST['password']??'';
    if($id>0){
        if($pass!==''){ $hash=password_hash($pass,PASSWORD_DEFAULT); $stmt=$conn->prepare('UPDATE users SET full_name=?, email=?, role=?, phone_number=?, account_status=?, password_hash=? WHERE user_id=?'); $stmt->bind_param('ssssssi',$name,$email,$role,$phone,$status,$hash,$id); }
        else { $stmt=$conn->prepare('UPDATE users SET full_name=?, email=?, role=?, phone_number=?, account_status=? WHERE user_id=?'); $stmt->bind_param('sssssi',$name,$email,$role,$phone,$status,$id); }
        $stmt->execute(); $msg='User updated';
    } else {
        $hash=password_hash($pass ?: 'password123', PASSWORD_DEFAULT); $stmt=$conn->prepare('INSERT INTO users(full_name,email,password_hash,role,phone_number,email_verified,account_status) VALUES(?,?,?,?,?,1,?)'); $stmt->bind_param('ssssss',$name,$email,$hash,$role,$phone,$status); $stmt->execute(); $msg='User added';
    }
    header('Location: admin_manage_users.php?success='.urlencode($msg)); exit;
}
$users=$conn->query('SELECT * FROM users ORDER BY role, full_name'); $page_title='Admin Manage User Accounts'; $active_page='users'; include __DIR__ . '/includes/header.php';
?>
<div class="mb-8"><h1 class="text-4xl font-black text-[#36000f]">Admin - Manage User Accounts</h1><p class="text-slate-500 mt-2">Add, update, suspend or delete student, staff, facility manager and admin accounts.</p></div>
<div class="grid grid-cols-1 xl:grid-cols-3 gap-6"><form method="post" class="bg-white rounded-xl border border-[#dcc0c2] p-6 shadow-sm space-y-4"><h2 class="text-xl font-black text-[#36000f]"><?= $edit?'Update User':'Add User' ?></h2><input type="hidden" name="user_id" value="<?= h($edit['user_id']??0) ?>"><input class="input" name="full_name" required placeholder="Full name" value="<?= h($edit['full_name']??'') ?>"><input class="input" name="email" type="email" required placeholder="Email" value="<?= h($edit['email']??'') ?>"><input class="input" name="phone_number" placeholder="Phone number" value="<?= h($edit['phone_number']??'') ?>"><input class="input" name="password" type="password" placeholder="Password <?= $edit?'(leave blank to keep old)':'' ?>"><select class="input" name="role"><?php foreach(['student','staff','facility_manager','admin'] as $r): ?><option value="<?= $r ?>" <?= ($edit['role']??'student')===$r?'selected':'' ?>><?= ucwords(str_replace('_',' ',$r)) ?></option><?php endforeach; ?></select><select class="input" name="account_status"><?php foreach(['active','inactive','suspended'] as $s): ?><option value="<?= $s ?>" <?= ($edit['account_status']??'active')===$s?'selected':'' ?>><?= ucfirst($s) ?></option><?php endforeach; ?></select><button class="btn-primary w-full"><?= $edit?'Update User':'Add User' ?></button></form>
<div class="xl:col-span-2 bg-white rounded-xl border border-[#dcc0c2] shadow-sm overflow-hidden"><table class="w-full"><thead><tr><th class="table-th">User</th><th class="table-th">Role</th><th class="table-th">Status</th><th class="table-th">Action</th></tr></thead><tbody><?php while($u=$users->fetch_assoc()): ?><tr><td class="table-td font-bold"><?= h($u['full_name']) ?><p class="text-xs text-slate-500"><?= h($u['email']) ?> · <?= h($u['phone_number']) ?></p></td><td class="table-td"><?= h($u['role']) ?></td><td class="table-td"><span class="badge badge-<?= h($u['account_status']) ?>"><?= h($u['account_status']) ?></span></td><td class="table-td"><a class="text-red-900 font-bold" href="?edit=<?= h($u['user_id']) ?>">Edit</a><?php if((int)$u['user_id'] !== (int)$user['user_id']): ?> · <a class="text-red-700 font-bold" onclick="return confirm('Delete this user?')" href="?delete=<?= h($u['user_id']) ?>">Delete</a><?php endif; ?></td></tr><?php endwhile; ?></tbody></table></div></div>
<?php include __DIR__ . '/includes/footer.php'; ?>
