<?php
require_once __DIR__ . '/includes/auth.php';
$user = require_role(['admin']);
$back='admin_manage_users.php'; $id=(int)($_GET['id'] ?? 0);
if($_SERVER['REQUEST_METHOD']==='POST'){
    $verification = in_array($_POST['verification_status'] ?? '', ['unverified','verified'], true) ? $_POST['verification_status'] : 'unverified';
    $stmt=$conn->prepare('UPDATE users SET verification_status=? WHERE user_id=?'); $stmt->bind_param('si',$verification,$id); $stmt->execute();
    header('Location: admin_user_detail.php?id='.$id.'&success='.urlencode('Verification status updated')); exit;
}
$stmt=$conn->prepare('SELECT * FROM users WHERE user_id=? LIMIT 1'); $stmt->bind_param('i',$id); $stmt->execute(); $u=$stmt->get_result()->fetch_assoc();
if(!$u){ header('Location: '.$back.'?error='.urlencode('User not found')); exit; }
$page_title='User Detail'; $active_page='users'; include __DIR__ . '/includes/header.php';
$profile = !empty($u['profile_image_base64']) ? 'data:' . h($u['profile_image_mime'] ?: 'image/png') . ';base64,' . $u['profile_image_base64'] : 'https://ui-avatars.com/api/?name=' . urlencode($u['full_name'] ?? 'User') . '&background=5c001f&color=fff';
?>
<div class="mb-8 flex justify-between items-end"><div><h1 class="text-4xl font-black text-[#36000f]">User Detail</h1><p class="text-slate-500 mt-2">View profile picture, UTM card and edit verification status.</p></div><a class="btn-light" href="<?= h($back) ?>">Back</a></div>
<div class="grid lg:grid-cols-3 gap-6"><div class="bg-white rounded-xl border border-[#dcc0c2] p-6 shadow-sm"><h2 class="text-xl font-black text-[#36000f] mb-4">Profile Picture</h2><img src="<?= $profile ?>" class="w-full max-h-72 object-cover rounded-xl border" alt="Profile picture"></div><div class="lg:col-span-2 bg-white rounded-xl border border-[#dcc0c2] p-6 shadow-sm"><h2 class="text-xl font-black text-[#36000f] mb-4">Account Information</h2><div class="grid sm:grid-cols-2 gap-4"><div><p class="text-xs uppercase font-bold text-slate-500">User ID</p><p class="font-bold"><?= h($u['user_id']) ?></p></div><div><p class="text-xs uppercase font-bold text-slate-500">Full name</p><p class="font-bold"><?= h($u['full_name']) ?></p></div><div><p class="text-xs uppercase font-bold text-slate-500">Email</p><p><?= h($u['email']) ?></p></div><div><p class="text-xs uppercase font-bold text-slate-500">Phone</p><p><?= h($u['phone_number']) ?></p></div><div><p class="text-xs uppercase font-bold text-slate-500">UTM ID</p><p><?= h($u['utm_id']) ?></p></div><div><p class="text-xs uppercase font-bold text-slate-500">IC No</p><p><?= h($u['ic_no']) ?></p></div><div><p class="text-xs uppercase font-bold text-slate-500">Role</p><p><?= h(ucwords(str_replace('_',' ',$u['role']))) ?></p></div><div><p class="text-xs uppercase font-bold text-slate-500">Account status</p><span class="badge badge-<?= h($u['account_status']) ?>"><?= h($u['account_status']) ?></span></div></div><form method="post" class="mt-6 flex gap-3 items-end"><div><label class="text-xs uppercase font-bold text-slate-500">Verification Status</label><select class="input" name="verification_status"><option value="unverified" <?= ($u['verification_status']??'unverified')==='unverified'?'selected':'' ?>>Unverified</option><option value="verified" <?= ($u['verification_status']??'unverified')==='verified'?'selected':'' ?>>Verified</option></select></div><button class="btn-primary">Update Verification</button></form></div></div>
<div class="mt-6 bg-white rounded-xl border border-[#dcc0c2] p-6 shadow-sm"><h2 class="text-xl font-black text-[#36000f] mb-4">UTM Card</h2><div class="grid md:grid-cols-2 gap-6"><?php if(!empty($u['utm_card_base64'])): ?><div><p class="text-xs uppercase font-bold text-slate-500 mb-2">Front Side</p><img src="data:<?= h($u['utm_card_mime'] ?: 'image/png') ?>;base64,<?= $u['utm_card_base64'] ?>" class="max-w-xl w-full rounded-xl border" alt="UTM card front"></div><?php else: ?><div><p class="text-slate-500">No front card uploaded.</p></div><?php endif; ?><?php if(!empty($u['utm_card_back_base64'])): ?><div><p class="text-xs uppercase font-bold text-slate-500 mb-2">Back Side</p><img src="data:<?= h($u['utm_card_back_mime'] ?: 'image/png') ?>;base64,<?= $u['utm_card_back_base64'] ?>" class="max-w-xl w-full rounded-xl border" alt="UTM card back"></div><?php else: ?><div><p class="text-slate-500">No back card uploaded.</p></div><?php endif; ?></div></div>
<?php include __DIR__ . '/includes/footer.php'; ?>
