<?php
require_once __DIR__ . '/includes/auth.php';
$user = require_role(['facility_manager']);
$conn->query("CREATE TABLE IF NOT EXISTS schedules (schedule_id INT AUTO_INCREMENT PRIMARY KEY, resource_type ENUM('room','facility') NOT NULL, room_id INT NULL, facility_id INT NULL, start_time DATETIME NOT NULL, end_time DATETIME NOT NULL, status ENUM('available','blocked','maintenance') NOT NULL DEFAULT 'available', notes VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)");
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; $stmt=$conn->prepare('DELETE FROM schedules WHERE schedule_id=?'); $stmt->bind_param('i',$id); $stmt->execute(); header('Location: manager_manage_schedules.php?success=Schedule deleted'); exit; }
$edit=null; if(isset($_GET['edit'])){ $id=(int)$_GET['edit']; $stmt=$conn->prepare('SELECT * FROM schedules WHERE schedule_id=?'); $stmt->bind_param('i',$id); $stmt->execute(); $edit=$stmt->get_result()->fetch_assoc(); }
if($_SERVER['REQUEST_METHOD']==='POST'){
    $id=(int)($_POST['schedule_id']??0); $rtype=$_POST['resource_type']; $rid=(int)$_POST['resource_id']; $room_id=$rtype==='room'?$rid:null; $facility_id=$rtype==='facility'?$rid:null; $start=$_POST['start_time']; $end=$_POST['end_time']; $status=$_POST['status']; $notes=trim($_POST['notes']);
    if($id>0){ $stmt=$conn->prepare('UPDATE schedules SET resource_type=?,room_id=?,facility_id=?,start_time=?,end_time=?,status=?,notes=? WHERE schedule_id=?'); $stmt->bind_param('siissssi',$rtype,$room_id,$facility_id,$start,$end,$status,$notes,$id); $stmt->execute(); $msg='Schedule updated'; }
    else { $stmt=$conn->prepare('INSERT INTO schedules(resource_type,room_id,facility_id,start_time,end_time,status,notes) VALUES(?,?,?,?,?,?,?)'); $stmt->bind_param('siissss',$rtype,$room_id,$facility_id,$start,$end,$status,$notes); $stmt->execute(); $msg='Schedule added'; }
    header('Location: manager_manage_schedules.php?success='.urlencode($msg)); exit;
}
$rooms=$conn->query('SELECT room_id, room_name FROM rooms ORDER BY room_name'); $facilities=$conn->query('SELECT facility_id, facility_name FROM facilities ORDER BY facility_name');
$schedules=$conn->query("SELECT s.*, COALESCE(r.room_name,f.facility_name) resource_name FROM schedules s LEFT JOIN rooms r ON r.room_id=s.room_id LEFT JOIN facilities f ON f.facility_id=s.facility_id ORDER BY s.start_time DESC");
$page_title='Facility Manager Manage Schedules'; $active_page='schedules'; include __DIR__ . '/includes/header.php';
?>
<div class="mb-8"><h1 class="text-4xl font-black text-[#36000f]">Facility Manager - Add / Update / Delete Schedules</h1><p class="text-slate-500 mt-2">Block resources for availability or maintenance. Add, update or delete blocked/maintenance schedule records.</p></div>
<div class="grid grid-cols-1 xl:grid-cols-3 gap-6"><form method="post" class="bg-white rounded-xl border border-[#dcc0c2] p-6 shadow-sm space-y-4"><h2 class="text-xl font-black text-[#36000f]"><?= $edit?'Update Schedule':'Add Schedule' ?></h2><input type="hidden" name="schedule_id" value="<?= h($edit['schedule_id']??0) ?>"><select class="input" name="resource_type" id="rtype" onchange="toggleResource()"><option value="room" <?= ($edit['resource_type']??'room')==='room'?'selected':'' ?>>Room</option><option value="facility" <?= ($edit['resource_type']??'room')==='facility'?'selected':'' ?>>Facility</option></select><select class="input" id="room_select"><option value="">Choose room</option><?php while($r=$rooms->fetch_assoc()): ?><option value="<?= h($r['room_id']) ?>" <?= (int)($edit['room_id']??0)===(int)$r['room_id']?'selected':'' ?>><?= h($r['room_name']) ?></option><?php endwhile; ?></select><select class="input hidden" id="facility_select"><option value="">Choose facility</option><?php while($f=$facilities->fetch_assoc()): ?><option value="<?= h($f['facility_id']) ?>" <?= (int)($edit['facility_id']??0)===(int)$f['facility_id']?'selected':'' ?>><?= h($f['facility_name']) ?></option><?php endwhile; ?></select><input type="hidden" name="resource_id" id="resource_id" required><input class="input" name="start_time" type="datetime-local" required value="<?= $edit?date('Y-m-d\TH:i', strtotime($edit['start_time'])):'' ?>"><input class="input" name="end_time" type="datetime-local" required value="<?= $edit?date('Y-m-d\TH:i', strtotime($edit['end_time'])):'' ?>"><select class="input" name="status"><?php foreach(['available','blocked','maintenance'] as $st): ?><option value="<?= $st ?>" <?= ($edit['status']??'available')===$st?'selected':'' ?>><?= ucfirst($st) ?></option><?php endforeach; ?></select><textarea class="input" name="notes" placeholder="Notes"><?= h($edit['notes']??'') ?></textarea><button class="btn-primary w-full" onclick="syncResource()"><?= $edit?'Update Schedule':'Add Schedule' ?></button></form>
<div class="xl:col-span-2 bg-white rounded-xl border border-[#dcc0c2] shadow-sm overflow-hidden"><table class="w-full"><thead><tr><th class="table-th">Resource</th><th class="table-th">Start</th><th class="table-th">End</th><th class="table-th">Status</th><th class="table-th">Action</th></tr></thead><tbody><?php while($s=$schedules->fetch_assoc()): ?><tr><td class="table-td font-bold"><?= h($s['resource_name']) ?><p class="text-xs text-slate-500"><?= h($s['notes']) ?></p></td><td class="table-td"><?= h($s['start_time']) ?></td><td class="table-td"><?= h($s['end_time']) ?></td><td class="table-td"><span class="badge badge-<?= h($s['status']) ?>"><?= h($s['status']) ?></span></td><td class="table-td"><a class="text-red-900 font-bold" href="?edit=<?= h($s['schedule_id']) ?>">Edit</a> · <a class="text-red-700 font-bold" onclick="return confirm('Delete this schedule?')" href="?delete=<?= h($s['schedule_id']) ?>">Delete</a></td></tr><?php endwhile; ?></tbody></table></div></div>
<script>function toggleResource(){let t=document.getElementById('rtype').value;document.getElementById('room_select').classList.toggle('hidden',t!=='room');document.getElementById('facility_select').classList.toggle('hidden',t!=='facility');syncResource()}function syncResource(){let t=document.getElementById('rtype').value;document.getElementById('resource_id').value=document.getElementById(t+'_select').value}document.getElementById('room_select').onchange=syncResource;document.getElementById('facility_select').onchange=syncResource;syncResource();</script>
<?php include __DIR__ . '/includes/footer.php'; ?>
